### ISSUE TITLE
Large complex sheet may show no highlighting

### ISSUE THREAD

**Issue by nrichards** [matsu7089/sheets-row-highlighter#1]
**Reproduction**
* row-highlighter version 1.1.2 March 15 2021
* MacBook Pro (15-inch, 2018), 2.9 GHz 6-Core Intel Core i9, 32 GB 2400 MHz DDR4
* MacOS 11.2.2
* Firefox 86.0.1
* Disabled uBlock Origin extension
* Open https://docs.google.com/spreadsheets/d/1Rq3RCYELRs95yISdlrkcUP-rNG4kZN7k3APNlaKDe6I/edit#gid=0 example
* OPTIONAL: Reload page using browser Reload button

**Expected**
* See highlighted rows and columns

**Actual**
* See normal color, white, without highlight colors

**Workaround**
* Simplify the text in Column "A" to "hello" for all Rows (paste all)

**Discussion**
* May be a timing issue 
* Is difficult to make a spreadsheet that does not show highlighting correctly. I believe the complexity of this example sheet is the reason it does not render correctly.

**Comment by matsu7089** [comment]
Thanks for the detailed report!

I have opened the example sheet but it is highlighted.
It may take some time to resolve this issue.
I will continue to investigate.

**Comment by matsu7089** [comment]
@nrichards 
Sorry for the delay.
With the recent release of v2, I've updated the logic for highlighting, which should resolve the problem.
If you're still experiencing issues, please don't hesitate to create a new issue so I can investigate further.
I appreciate your feedback and thank you for bringing this to my attention!
