### ISSUE TITLE
Not Working - Not Sure How to Troubleshoot

### ISSUE THREAD

**Issue by DrSuSE** [matsu7089/sheets-row-highlighter#2]
I cannot seem to make this work... new and existing Google Sheets.  Standard and Workspace accounts.  Windows 11, Firefox 105.0.3.

Not sure how I can troubleshoot.  The little popdown menu works fine, I can set options, etc... but the highlighting doesn't actually happen.  Tried restarting Firefox, restarting the PC, clearing cookies, trying in a Private window, etc.

**Comment by DrSuSE** [comment]
All my sheets work fine with the Chrome extension, so this seems to be an issue with the Firefox extension.

**Comment by matsu7089** [comment]
@DrSuSE 
Sorry for the delay.
With the recent release of v2, I've updated the logic for highlighting, which should resolve the problem.
If you're still experiencing issues, please don't hesitate to create a new issue so I can investigate further.
I appreciate your feedback and thank you for bringing this to my attention!
