### ISSUE TITLE
[Feature request] Disable highlight automatically and a shortcut to trigger highlighting

### ISSUE THREAD

**Issue by nh314** [matsu7089/sheets-row-highlighter#3]
Thank you for this amazing extension.
In my opinion,  It would be nice if we have these features in the next update of the extension:
- Add a checkbox to enable/disable highlight automatically.
- Keyboard shortcut to trigger highlighting.

**Comment by matsu7089** [comment]
@nh314 
Thank you for submitting your feature request!
In the recently released v2.1, I've added the automatic highlight feature and a shortcut to toggle highlighting for both rows and columns.
Thank you for your feedback and support!
